!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : PI_AntiWindUp_50_2_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE PI_AntiWindUp_50_2_1Dyn(In, Out, frz, Rst, Kp, Ti,     &
     &   Kaw, MaxOut, MinOut)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
      REAL    LIMIT         ! Hard Limiter

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: frz, Rst
      REAL,    INTENT(IN)  :: In, Kp, Ti, Kaw
      REAL,    INTENT(IN)  :: MaxOut, MinOut
      REAL,    INTENT(OUT) :: Out

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 3
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 18
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Out      = STOF(ISTOF + 2)
      RT_1     = STOF(ISTOF + 8)
      RT_2     = STOF(ISTOF + 9)
      RT_3     = STOF(ISTOF + 10)
      RT_4     = STOF(ISTOF + 11)
      RT_5     = STOF(ISTOF + 12)
      RT_6     = STOF(ISTOF + 13)
      IT_1     = STOI(ISTOI + 3)
      RT_7     = STOF(ISTOF + 14)
      RT_8     = STOF(ISTOF + 15)
      RT_9     = STOF(ISTOF + 16)
      RT_10    = STOF(ISTOF + 17)
      RT_11    = STOF(ISTOF + 18)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PI_AntiWindUp_50_2_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[deadband_34_2_1] Deadband with offset and gain 
      RT_6 = 0.0
      IF (In .GT. RTCF(NRTCF)) THEN
        RT_6 = RTCF(NRTCF+1)*(In - RTCF(NRTCF)) +  RTCF(NRTCF+2)
      ELSEIF (In .LT. -RTCF(NRTCF)) THEN
        RT_6 = RTCF(NRTCF+1)*(In + RTCF(NRTCF)) -  RTCF(NRTCF+2)
      ENDIF
      NRTCF = NRTCF + 3

! 90:[const] Real Constant 
      RT_11 = 0.0

! 110:[gain] Gain Block 
!  Gain
      RT_9 = Kaw * RT_8

! 120:[inv] Interpolated Logic Inverter 
      IF (Rst .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 130:[mult] Multiplier 
      RT_4 = RT_6 * REAL(IT_1)

! 140:[gain] Gain Block 
!  Gain
      RT_3 = Kp * RT_4

! 150:[sumjct] Summing/Differencing Junctions 
      RT_10 = + RT_9 + RT_6

! 160:[select] Two Input Selector 
      IF (frz .EQ. RTCI(NRTCI)) THEN
         RT_5 = RT_11
      ELSE
         RT_5 = RT_10
      ENDIF
      NRTCI = NRTCI + 1
!

! 170:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_5
      RVD2_1(2) = 0.0
      RVD2_2(1) = FLOAT(Rst)
      RVD2_2(2) = 0.0
      RT_2 = EMTDC_XINT(0, 0, 1, RVD1_1, Ti, 0.0, MinOut, MaxOut, RVD2_2&
     &, RVD2_1)

! 180:[sumjct] Summing/Differencing Junctions 
      RT_1 = + RT_2 + RT_3

! 190:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (MinOut .LE. MaxOut) THEN
        Out = LIMIT(MinOut, MaxOut, RT_1)
      ELSE
        Out = RT_1
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,2116304486,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 200:[sumjct] Summing/Differencing Junctions 
      RT_7 = - RT_1 + Out

! 220:[zminusone] Feedback Loop Selector 'Feedback Loop XYZ'
! Feedback Loop XYZ
      RT_8 = RT_7

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = In
      STOF(ISTOF + 2) = Out
      STOI(ISTOI + 1) = frz
      STOI(ISTOI + 2) = Rst
      STOF(ISTOF + 3) = Kp
      STOF(ISTOF + 4) = Ti
      STOF(ISTOF + 5) = Kaw
      STOF(ISTOF + 6) = MaxOut
      STOF(ISTOF + 7) = MinOut
      STOF(ISTOF + 8) = RT_1
      STOF(ISTOF + 9) = RT_2
      STOF(ISTOF + 10) = RT_3
      STOF(ISTOF + 11) = RT_4
      STOF(ISTOF + 12) = RT_5
      STOF(ISTOF + 13) = RT_6
      STOI(ISTOI + 3) = IT_1
      STOF(ISTOF + 14) = RT_7
      STOF(ISTOF + 15) = RT_8
      STOF(ISTOF + 16) = RT_9
      STOF(ISTOF + 17) = RT_10
      STOF(ISTOF + 18) = RT_11


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Out      is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PI_AntiWindUp_50_2_1Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_11    = STOF(ISTOF + 18)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PI_AntiWindUp_50_2_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 90:[const] Real Constant 

      RT_11 = 0.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 18) = RT_11


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PI_AntiWindUp_50_2_1Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[deadband_34_2_1] Deadband with offset and gain 
      RTCF(NRTCF)   = 0.5*ABS(0.005)
      RTCF(NRTCF+1) = ABS(1.0)
      RTCF(NRTCF+2) = ABS(0.0)
      NRTCF = NRTCF + 3

! 90:[const] Real Constant 
      RT_11 = 0.0

! 110:[gain] Gain Block 

! 120:[inv] Interpolated Logic Inverter 

! 130:[mult] Multiplier 

! 140:[gain] Gain Block 

! 150:[sumjct] Summing/Differencing Junctions 

! 160:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 170:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 180:[sumjct] Summing/Differencing Junctions 

! 190:[hardlimit] Hard Limiter 

! 200:[sumjct] Summing/Differencing Junctions 

! 220:[zminusone] Feedback Loop Selector 'Feedback Loop XYZ'

      RETURN
      END

!=======================================================================

      SUBROUTINE PI_AntiWindUp_50_2_1Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 90:[const] Real Constant 
      RT_11 = 0.0

      RETURN
      END

